import os
from tvm import te


def batch_matmul_nn_192x5x5x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=6)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=5)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=64)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=5)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=1)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=1)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=1)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=6)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=5)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=1)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=1)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=1)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=64)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=1)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=64)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=64)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 512)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


def batch_matmul_nn_192x24x24x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=2)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=3)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=4)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=32)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=2)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=2)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=3)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=1)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=1)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=1)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=2)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=3)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=4)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=1)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=32)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=2)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=96)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=96)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 512)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


def batch_matmul_nn_192x43x43x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=43)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=4)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=8)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=2)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=43)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=1)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=1)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=1)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=1)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=1)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=43)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=1)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=4)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=8)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=2)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=344)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=344)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 16)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


def batch_matmul_nn_192x62x62x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=2)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=31)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=2)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=2)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=8)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=2)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=2)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=31)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=1)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=1)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=1)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=2)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=31)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=1)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=4)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=8)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=2)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=4)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=248)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=2)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=248)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 1024)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


def batch_matmul_nn_192x81x81x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=2)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=3)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=3)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=9)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=2)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=32)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=1)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=3)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=2)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=3)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=1)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=27)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=1)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=1)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=2)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=32)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=1)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=2)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=96)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=96)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 1024)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


def batch_matmul_nn_192x100x100x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=10)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=10)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=4)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=16)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=2)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=10)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=1)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=1)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=1)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=10)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=10)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=1)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=4)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=16)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=1)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=4)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=160)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=2)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=160)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 1024)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


def batch_matmul_nn_192x119x119x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=2)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=8)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=17)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=4)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=16)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=1)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=7)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=2)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=8)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=1)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=17)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=1)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=1)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=4)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=16)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=1)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=4)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=128)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=128)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 1024)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


def batch_matmul_nn_192x128x128x64(X, W, T_batch_matmul_NN, s):
    T_batch_matmul_NN_b, T_batch_matmul_NN_i, T_batch_matmul_NN_j, T_batch_matmul_NN_k = tuple(T_batch_matmul_NN.op.axis) + tuple(T_batch_matmul_NN.op.reduce_axis)
    T_batch_matmul_NN_local, = s.cache_write([T_batch_matmul_NN], "local")
    T_batch_matmul_NN_local_b_c, T_batch_matmul_NN_local_i_c, T_batch_matmul_NN_local_j_c, T_batch_matmul_NN_local_k = tuple(T_batch_matmul_NN_local.op.axis) + tuple(T_batch_matmul_NN_local.op.reduce_axis)
    T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_b_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_b_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_i, factor=1)
    T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_b_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_i_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c, factor=2)
    T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_i_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_i, factor=8)
    T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_i, factor=8)
    T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_i_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_j_c_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c, factor=1)
    T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_j_c_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_i, factor=4)
    T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_i, factor=16)
    T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_j_c_o_o_o_i, factor=1)
    T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_k_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k, factor=2)
    T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i = s[T_batch_matmul_NN_local].split(T_batch_matmul_NN_local_k_o_i, factor=16)
    s[T_batch_matmul_NN_local].reorder(T_batch_matmul_NN_local_b_c_o_o_o_o, T_batch_matmul_NN_local_i_c_o_o_o_o, T_batch_matmul_NN_local_j_c_o_o_o_o, T_batch_matmul_NN_local_b_c_o_o_o_i, T_batch_matmul_NN_local_i_c_o_o_o_i, T_batch_matmul_NN_local_j_c_o_o_o_i, T_batch_matmul_NN_local_b_c_o_o_i, T_batch_matmul_NN_local_i_c_o_o_i, T_batch_matmul_NN_local_j_c_o_o_i, T_batch_matmul_NN_local_k_o_o, T_batch_matmul_NN_local_k_o_i, T_batch_matmul_NN_local_b_c_o_i, T_batch_matmul_NN_local_i_c_o_i, T_batch_matmul_NN_local_j_c_o_i, T_batch_matmul_NN_local_k_i, T_batch_matmul_NN_local_b_c_i, T_batch_matmul_NN_local_i_c_i, T_batch_matmul_NN_local_j_c_i)
    T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_b_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b, factor=1)
    T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_b_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_i, factor=1)
    T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_b_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_b_o_o_i, factor=1)
    T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_i_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i, factor=16)
    T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_i_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_i, factor=8)
    T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_i_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_i_o_o_i, factor=1)
    T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_j_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j, factor=4)
    T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_j_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_i, factor=16)
    T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_j_o_o_i = s[T_batch_matmul_NN].split(T_batch_matmul_NN_j_o_o_i, factor=1)
    s[T_batch_matmul_NN].reorder(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o, T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i, T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i, T_batch_matmul_NN_b_i, T_batch_matmul_NN_i_i, T_batch_matmul_NN_j_i)
    s[T_batch_matmul_NN_local].compute_at(s[T_batch_matmul_NN], T_batch_matmul_NN_j_o_i)
    W_shared = s.cache_read(W, "shared", [T_batch_matmul_NN_local])
    W_shared_ax0, W_shared_ax1, W_shared_ax2 = tuple(W_shared.op.axis)
    s[W_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    X_shared = s.cache_read(X, "shared", [T_batch_matmul_NN_local])
    X_shared_ax0, X_shared_ax1, X_shared_ax2 = tuple(X_shared.op.axis)
    s[X_shared].compute_at(s[T_batch_matmul_NN_local], T_batch_matmul_NN_local_k_o_o)
    T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_o, T_batch_matmul_NN_i_o_o_o, T_batch_matmul_NN_j_o_o_o)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_o_i_o_o_o_fused_j_o_o_o_fused, te.thread_axis("blockIdx.x"))
    T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_o_i, T_batch_matmul_NN_i_o_o_i, T_batch_matmul_NN_j_o_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_o_i_i_o_o_i_fused_j_o_o_i_fused, te.thread_axis("vthread"))
    T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused = s[T_batch_matmul_NN].fuse(T_batch_matmul_NN_b_o_i, T_batch_matmul_NN_i_o_i, T_batch_matmul_NN_j_o_i)
    s[T_batch_matmul_NN].bind(T_batch_matmul_NN_b_o_i_i_o_i_fused_j_o_i_fused, te.thread_axis("threadIdx.x"))
    W_shared_ax0_ax1_fused_ax2_fused = s[W_shared].fuse(W_shared_ax0, W_shared_ax1, W_shared_ax2)
    W_shared_ax0_ax1_fused_ax2_fused_o, W_shared_ax0_ax1_fused_ax2_fused_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[W_shared].vectorize(W_shared_ax0_ax1_fused_ax2_fused_i)
    W_shared_ax0_ax1_fused_ax2_fused_o_o, W_shared_ax0_ax1_fused_ax2_fused_o_i = s[W_shared].split(W_shared_ax0_ax1_fused_ax2_fused_o, factor=128)
    s[W_shared].bind(W_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    X_shared_ax0_ax1_fused_ax2_fused = s[X_shared].fuse(X_shared_ax0, X_shared_ax1, X_shared_ax2)
    X_shared_ax0_ax1_fused_ax2_fused_o, X_shared_ax0_ax1_fused_ax2_fused_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused, factor=1)
    s[X_shared].vectorize(X_shared_ax0_ax1_fused_ax2_fused_i)
    X_shared_ax0_ax1_fused_ax2_fused_o_o, X_shared_ax0_ax1_fused_ax2_fused_o_i = s[X_shared].split(X_shared_ax0_ax1_fused_ax2_fused_o, factor=128)
    s[X_shared].bind(X_shared_ax0_ax1_fused_ax2_fused_o_i, te.thread_axis("threadIdx.x"))
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "auto_unroll_max_step", 2048 if int(os.getenv("USE_NIMBLE", "0")) else 512)
    s[T_batch_matmul_NN_local].pragma(T_batch_matmul_NN_local_b_c_o_o_o_o, "unroll_explicit", True)


